name: store_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  auto_route: ^10.1.2
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  auto_route_generator: ^10.2.4

flutter:
  uses-material-design: true

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/fonts/sour_gummy/SourGummy-Thin.ttf
          weight: 100
        - asset: assets/fonts/sour_gummy/SourGummy-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sour_gummy/SourGummy-Light.ttf
          weight: 300
        - asset: assets/fonts/sour_gummy/SourGummy-Regular.ttf
          weight: 400
        - asset: assets/fonts/sour_gummy/SourGummy-Medium.ttf
          weight: 500
        - asset: assets/fonts/sour_gummy/SourGummy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sour_gummy/SourGummy-Bold.ttf
          weight: 700
        - asset: assets/fonts/sour_gummy/SourGummy-ExtraBold.ttf
          weight: 800
